version: '3.8'

services:
  web:
    build:  
      context: .
      dockerfile: Dockerfile
    container_name: web
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    command: python app.py
